-- Generated by Oracle SQL Developer Data Modeler 19.4.0.350.1424
--   at:        2020-05-05 15:38:20 CEST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



CREATE TABLE "176553_adresy_hodowli" (
    id           INTEGER NOT NULL,
    numer        VARCHAR2(50) NOT NULL,
    ulica        VARCHAR2(50) NOT NULL,
    kod          CHAR(6) NOT NULL,
    miejscowosc  VARCHAR2(50) NOT NULL
);

COMMENT ON TABLE "176553_adresy_hodowli" IS
    'Przechwuje adresy wszystkich hodowcow';

ALTER TABLE "176553_adresy_hodowli" ADD CONSTRAINT "176553_adresy_hodowli_PK" PRIMARY KEY ( id );

CREATE TABLE "176553_adresy_pracownikow" (
    id           INTEGER NOT NULL,
    ulica        VARCHAR2(50) NOT NULL,
    numer        VARCHAR2(50) NOT NULL,
    kod          CHAR(6) NOT NULL,
    miejscowosc  VARCHAR2(50) NOT NULL
);

COMMENT ON TABLE "176553_adresy_pracownikow" IS
    'Przechwuje adresy wszystkich pracownikow';

ALTER TABLE "176553_adresy_pracownikow" ADD CONSTRAINT adresy_pracownikow_pk PRIMARY KEY ( id );

CREATE TABLE "176553_hodowle" (
    id                          INTEGER NOT NULL,
    nazwa                       VARCHAR2(50) NOT NULL,
    opis                        VARCHAR2(500),
    "176553_adresy_hodowli_id"  INTEGER NOT NULL
);

COMMENT ON TABLE "176553_hodowle" IS
    'Przechowuje informacje o hodowcach';

ALTER TABLE "176553_hodowle" ADD CONSTRAINT "176553_hodowle_PK" PRIMARY KEY ( id );

ALTER TABLE "176553_hodowle" ADD CONSTRAINT "176553_hodowle__UN" UNIQUE ( nazwa );

CREATE TABLE "176553_kategorie" (
    id         INTEGER NOT NULL,
    nazwa      VARCHAR2(50) NOT NULL,
    opis       VARCHAR2(500),
    zalecenia  VARCHAR2(500)
);

COMMENT ON TABLE "176553_kategorie" IS
    'Przechowuje informacje o kategoriach posiadanych zwierzat.';

ALTER TABLE "176553_kategorie" ADD CONSTRAINT "176553_kategorie_PK" PRIMARY KEY ( id );

ALTER TABLE "176553_kategorie" ADD CONSTRAINT "176553_kategorie__UN" UNIQUE ( nazwa );

CREATE TABLE "176553_opieka" (
    "176553_pracownicy_id"  INTEGER NOT NULL,
    "176553_zwierzeta_nr"   INTEGER NOT NULL
);

COMMENT ON TABLE "176553_opieka" IS
    'Przechowuje informacje o opiekunach posiadanych zwierzat.';

ALTER TABLE "176553_opieka" ADD CONSTRAINT "176553_opieka_PK" PRIMARY KEY ( "176553_pracownicy_id",
                                                                            "176553_zwierzeta_nr" );

CREATE TABLE "176553_platnosci" (
    id     INTEGER NOT NULL,
    nazwa  VARCHAR2(10) NOT NULL
);

COMMENT ON TABLE "176553_platnosci" IS
    'Przechowuje informacje o rodzaju danej platnosci..';

ALTER TABLE "176553_platnosci" ADD CONSTRAINT "176553_platnosc_PK" PRIMARY KEY ( id );

ALTER TABLE "176553_platnosci" ADD CONSTRAINT "176553_platnosc__UN" UNIQUE ( nazwa );

CREATE TABLE "176553_pracownicy" (
    id                     INTEGER NOT NULL,
    imie                   VARCHAR2(50) NOT NULL,
    nazwisko               VARCHAR2(50) NOT NULL,
    pesel                  CHAR(11) NOT NULL,
    nr_telefonu            NUMBER(9) NOT NULL,
    email                  VARCHAR2(50),
    "data zatrudnienia"    DATE,
    stanowiska_id          INTEGER NOT NULL,
    adresy_pracownikow_id  INTEGER NOT NULL
);

COMMENT ON TABLE "176553_pracownicy" IS
    'Przechowuje informacje o pracownikach.';

ALTER TABLE "176553_pracownicy" ADD CONSTRAINT pracownicy_pk PRIMARY KEY ( id );

ALTER TABLE "176553_pracownicy"
    ADD CONSTRAINT pracownicy__un UNIQUE ( pesel,
                                           nr_telefonu,
                                           email );

CREATE TABLE "176553_przypisanie" (
    "176553_zwierzeta_nr"  INTEGER NOT NULL,
    "176553_kategorie_id"  INTEGER NOT NULL
);

COMMENT ON TABLE "176553_przypisanie" IS
    'prypisanie zwierzat do ich kategorii.';

ALTER TABLE "176553_przypisanie" ADD CONSTRAINT "176553_przypisanie_PK" PRIMARY KEY ( "176553_zwierzeta_nr",
                                                                                      "176553_kategorie_id" );

CREATE TABLE "176553_stanowiska" (
    id      INTEGER NOT NULL,
    nazwa   VARCHAR2(50) NOT NULL,
    pensja  NUMBER(7, 2) NOT NULL,
    opis    VARCHAR2(500)
);

COMMENT ON TABLE "176553_stanowiska" IS
    'Przechowuje informacje o  stanowiskach.';

ALTER TABLE "176553_stanowiska" ADD CONSTRAINT stanowiska_pk PRIMARY KEY ( id );

ALTER TABLE "176553_stanowiska" ADD CONSTRAINT stanowiska__un UNIQUE ( nazwa );

CREATE TABLE "176553_transakcje" (
    "176553_transakcje_id"  INTEGER NOT NULL,
    "176553_zwierzeta_nr"   INTEGER NOT NULL,
    cena_laczna             NUMBER(7, 2) NOT NULL,
    sztuk                   INTEGER NOT NULL
);

COMMENT ON TABLE "176553_transakcje" IS
    'Przechowuje informacje o  transakcjach.';

ALTER TABLE "176553_transakcje" ADD CONSTRAINT "176553_pozycje_PK1" PRIMARY KEY ( "176553_transakcje_id",
                                                                                 "176553_zwierzeta_nr" );

CREATE TABLE "176553_transakcje_szczegoly" (
    id                      INTEGER NOT NULL,
    data_sprzedazy          DATE NOT NULL,
    godzina_sprzedazy       DATE,
    "176553_pracownicy_id"  INTEGER NOT NULL,
    "176553_platnosc_id"    INTEGER NOT NULL
);

COMMENT ON TABLE "176553_transakcje_szczegoly" IS
    'Przechowuje informacje o szczegolach  transakcji.';

ALTER TABLE "176553_transakcje_szczegoly" ADD CONSTRAINT "176553_transakcje_PK" PRIMARY KEY ( id );

CREATE TABLE "176553_zwierzeta" (
    nr                   INTEGER NOT NULL,
    nazwa                VARCHAR2(50) NOT NULL,
    cena                 NUMBER(7, 2) NOT NULL,
    ilosc                INTEGER NOT NULL,
    "176553_hodowle_id"  INTEGER NOT NULL
);

COMMENT ON TABLE "176553_zwierzeta" IS
    'Przechowuje informacje o zwierzetach na sprzedaz.';

ALTER TABLE "176553_zwierzeta" ADD CONSTRAINT "176553_zwierzeta_PK" PRIMARY KEY ( nr );

ALTER TABLE "176553_zwierzeta" ADD CONSTRAINT "176553_zwierzeta__UN" UNIQUE ( nazwa );

ALTER TABLE "176553_hodowle"
    ADD CONSTRAINT "176553_hodowle_adres" FOREIGN KEY ( "176553_adresy_hodowli_id" )
        REFERENCES "176553_adresy_hodowli" ( id );

ALTER TABLE "176553_opieka"
    ADD CONSTRAINT "176553_opieka_pracownicy_FK" FOREIGN KEY ( "176553_pracownicy_id" )
        REFERENCES "176553_pracownicy" ( id );

ALTER TABLE "176553_opieka"
    ADD CONSTRAINT "176553_opieka_zwierzeta_FK" FOREIGN KEY ( "176553_zwierzeta_nr" )
        REFERENCES "176553_zwierzeta" ( nr );

ALTER TABLE "176553_transakcje"
    ADD CONSTRAINT "176553_pozycje_transakcje_FK" FOREIGN KEY ( "176553_transakcje_id" )
        REFERENCES "176553_transakcje_szczegoly" ( id );

ALTER TABLE "176553_przypisanie"
    ADD CONSTRAINT "176553_przypisanie_kategorie" FOREIGN KEY ( "176553_kategorie_id" )
        REFERENCES "176553_kategorie" ( id );

ALTER TABLE "176553_przypisanie"
    ADD CONSTRAINT "176553_przypisanie_zwierzeta" FOREIGN KEY ( "176553_zwierzeta_nr" )
        REFERENCES "176553_zwierzeta" ( nr );

ALTER TABLE "176553_transakcje_szczegoly"
    ADD CONSTRAINT "176553_transakcje_platnosc_FK" FOREIGN KEY ( "176553_platnosc_id" )
        REFERENCES "176553_platnosci" ( id );

ALTER TABLE "176553_transakcje_szczegoly"
    ADD CONSTRAINT "176553_transakcje_pracownicy" FOREIGN KEY ( "176553_pracownicy_id" )
        REFERENCES "176553_pracownicy" ( id );

ALTER TABLE "176553_transakcje"
    ADD CONSTRAINT "176553_transakcje_zwierzeta_FK" FOREIGN KEY ( "176553_zwierzeta_nr" )
        REFERENCES "176553_zwierzeta" ( nr );

ALTER TABLE "176553_zwierzeta"
    ADD CONSTRAINT "176553_zwierzeta_hodowle_FK" FOREIGN KEY ( "176553_hodowle_id" )
        REFERENCES "176553_hodowle" ( id );

ALTER TABLE "176553_pracownicy"
    ADD CONSTRAINT pracownicy_adresy_fk FOREIGN KEY ( adresy_pracownikow_id )
        REFERENCES "176553_adresy_pracownikow" ( id );

ALTER TABLE "176553_pracownicy"
    ADD CONSTRAINT pracownicy_stanowiska_fk FOREIGN KEY ( stanowiska_id )
        REFERENCES "176553_stanowiska" ( id );

CREATE SEQUENCE "176553_adresy_hodowli_id_SEQ" START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER "176553_adresy_hodowli_id_TRG" BEFORE
    INSERT ON "176553_adresy_hodowli"
    FOR EACH ROW
    WHEN ( new.id IS NULL )
BEGIN
    :new.id := "176553_adresy_hodowli_id_SEQ".nextval;
END;
/

CREATE SEQUENCE "176553_adresy_pracownikow_id" START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER "176553_adresy_pracownikow_id" BEFORE
    INSERT ON "176553_adresy_pracownikow"
    FOR EACH ROW
    WHEN ( new.id IS NULL )
BEGIN
    :new.id := "176553_adresy_pracownikow_id".nextval;
END;
/

CREATE SEQUENCE "176553_hodowle_id_SEQ" START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER "176553_hodowle_id_TRG" BEFORE
    INSERT ON "176553_hodowle"
    FOR EACH ROW
    WHEN ( new.id IS NULL )
BEGIN
    :new.id := "176553_hodowle_id_SEQ".nextval;
END;
/

CREATE SEQUENCE "176553_kategorie_id_SEQ" START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER "176553_kategorie_id_TRG" BEFORE
    INSERT ON "176553_kategorie"
    FOR EACH ROW
    WHEN ( new.id IS NULL )
BEGIN
    :new.id := "176553_kategorie_id_SEQ".nextval;
END;
/

CREATE SEQUENCE "176553_platnosci_id_SEQ" START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER "176553_platnosci_id_TRG" BEFORE
    INSERT ON "176553_platnosci"
    FOR EACH ROW
    WHEN ( new.id IS NULL )
BEGIN
    :new.id := "176553_platnosci_id_SEQ".nextval;
END;
/

CREATE SEQUENCE "176553_pracownicy_id_SEQ" START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER "176553_pracownicy_id_TRG" BEFORE
    INSERT ON "176553_pracownicy"
    FOR EACH ROW
    WHEN ( new.id IS NULL )
BEGIN
    :new.id := "176553_pracownicy_id_SEQ".nextval;
END;
/

CREATE SEQUENCE "176553_stanowiska_id_SEQ" START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER "176553_stanowiska_id_TRG" BEFORE
    INSERT ON "176553_stanowiska"
    FOR EACH ROW
    WHEN ( new.id IS NULL )
BEGIN
    :new.id := "176553_stanowiska_id_SEQ".nextval;
END;
/

CREATE SEQUENCE "176553_transakcje_szczegoly_id" START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER "176553_transakcje_szczegoly_id" BEFORE
    INSERT ON "176553_transakcje_szczegoly"
    FOR EACH ROW
    WHEN ( new.id IS NULL )
BEGIN
    :new.id := "176553_transakcje_szczegoly_id".nextval;
END;
/

CREATE SEQUENCE "176553_zwierzeta_nr_SEQ" START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER "176553_zwierzeta_nr_TRG" BEFORE
    INSERT ON "176553_zwierzeta"
    FOR EACH ROW
    WHEN ( new.nr IS NULL )
BEGIN
    :new.nr := "176553_zwierzeta_nr_SEQ".nextval;
END;
/

CREATE TABLE rola (
id INTEGER NOT NULL PRIMARY KEY,
nazwa VARCHAR2(50) NOT NULL UNIQUE
);
INSERT INTO rola VALUES(1, 'Admin');
INSERT INTO rola VALUES(2, 'User');
/
CREATE TABLE konto (
 id INTEGER NOT NULL PRIMARY KEY,
 login VARCHAR2(50) NOT NULL UNIQUE,
 haslo VARCHAR2(100) NOT NULL,
 rola_id INTEGER NOT NULL
);
-- Uwaga: Ze wzglêdów dydaktycznych has³o przechowujemy jawnie.
INSERT INTO konto VALUES(1,'admin','admin',1);
INSERT INTO konto VALUES(2,'user','user',2);


-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            12
-- CREATE INDEX                             0
-- ALTER TABLE                             30
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           9
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          9
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
